## Terraform backend configuration for S3
## This file is auto generated by tfskel
## Verify the bucket name & make sure it exists in your AWS account.
## Verify other backend configuration as per your requirements before running 'terraform init'
## docs ref: https://developer.hashicorp.com/terraform/language/backend/s3
## Managed by tfskel — please keep the tfskel-metadata comment intact for bucket name management
## tfskel-metadata: {"bucket": "tfskel-terraform-demo-euc1-001"}

terraform {
  backend "s3" {
    bucket              = "tfskel-terraform-demo-euc1-001"
    key                 = "customer-1-dev-eu-central-1/terraform.tfstate"
    region              = "eu-central-1"
    encrypt             = true
    use_lockfile        = true
    allowed_account_ids = ["484941465042"]
  }
}
