## tfskel-source: {"template":"tf/versions.tf.tmpl","hash":"ec92411cd24742d5"}
## tfskel-metadata: {"aws_provider_ver":"~> 6.0","tf_ver":"~> 1.13.1"}
## tfskel-tags-hash: a7af6ef2ec897781
## Terraform providers and required versions
## This file is auto generated by tfskel

terraform {
  required_version = "~> 1.13.1"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 6.0"
    }
  }
}

provider "aws" {
  region = basename(dirname(path.cwd))

  default_tags {
    tags = {
      github_repo = "tfskel-demo"
      managed_by  = "terraform"
      env         = "dev"
      app         = "customer-1"
    }
  }
}
