## Terraform providers and required versions
## This file is auto generated by tfskel
## Managed by tfskel — please keep the tfskel-metadata & tfskel-tags comments intact for management
## tfskel-metadata: {"tf_ver": "~> 1.13.1", "aws_provider_ver": "~> 6.0"}
## tfskel-tags: {"github_repo":"tfskel-demo","managed_by":"terraform"}

terraform {
  required_version = "~> 1.13.1"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 6.0"
    }
  }
}

provider "aws" {
  region = basename(dirname(path.cwd))

  default_tags {
    tags = {
      github_repo = "tfskel-demo"
      managed_by  = "terraform"
      env         = "dev"
      app         = "customer-2"
    }
  }
}
